### PR TITLE
Allow switching to the international stream

### LINKED ISSUE #31: Add ability to change the `F1 Live` to `International` as the main feed
* [x] Handle the change to international in the layout for single-source streams
* [x] Handle offsets for int'l

Progress on this can be found in: #35

### LINKED ISSUE #34: Add ability to change the audio and subtitle track of the international stream
#31 will introduce the ability to change the `F1 Live` to `International` as the main feed. The international feed has multiple audio and subtitle tracks and we need a way to enable the user to change them.

CleanShot 2023-07-22 at 16 32 21@2x
CleanShot 2023-07-22 at 16 32 14@2x

### PR DESCRIPTION
**Pull request by bibixx**
Closes #31 
Closes #34

### CODE REVIEW

**Comment by bibixx** [comment]
@toiletgranny would you mind taking a look at this version?
Also if you'd be able to QA a little bit the int'l stream altogether that'd be great! Things like:
  * changing between stream types
  * what happens if you choose int'l in your layout and open a stream without support for int'l
  * offsets
    * there's a debug flag now to also set custom offsets for the int'l stream. I don't want to expose that to normal users though and use it only when creating Zium's shared offsets

**Comment by toiletgranny** [comment]
Oh, I totally forgot about the language selector for the international option. I like your separate button idea (perhaps we could iterate on the icon), but I also thought about bringing this all together under one dropdown. Something along the lines of the below screenshot. I know these are, technically, two different streams (F1 LIVE vs International), but from the user standpoint I feel like all we're doing is just changing the commentary. And so this led me into thinking we might as well try to display it like that. Let me know if you like this idea. 
image

In terms of QAing this, here's what I found:

> changing between stream types

Haven't observed any issues with that (🎉), but I think it would be great if my international language choice could be stored in local storage so that it can be carried over to other sessions throughout the app. Or even be preserved upon refreshing the window. I know that not all languages are available in all sessions, and, please, see my next point for an idea for how could go about it.

> what happens if you choose int'l in your layout and open a stream without support for int'l

I have briefly went through a couple of sessions from different seasons and I could not find a session that did not have support for int'l. Did you perhaps mean support for F1 LIVE? If not, could you clarify?

Anyway, continuing the idea from my previous point, in case a language set in the local storage is not available in a given session, I would just fall back to English (International), without changing it in the user's local storage. Let me know if it makes sense. 

> there's a debug flag now to also set custom offsets for the int'l stream. I don't want to expose that to normal users though and use it only when creating Zium's shared offsets

Yeah, I've noticed there's a shift between F1 LIVE and International. Shucks. Why can't software development be easy. 

Anyway, I totally agree on not showing this to all users and keeping it internal for now. Let's see where do we go from here.

**Comment by bibixx** [comment]
> And so this led me into thinking we might as well try to display it like that. Let me know if you like this idea.

I love the idea and I have actually already thought about doing that but it poses quite a big issue — I only have information about what languages are available **after** the user opens the international stream. So up until then I don't even know if there are any additional audio streams
  A solution could be that we display the languages instead of `International` after it has loaded but I think it won't be really discoverable

  I guess we could hardcoded those languages but I don't want to maintain that as I doubt I'll be using `International` myself too often (although I already fix what F1 does and I add diacritics to the language names, eg. Espanol (that's what F1 gives us) → Español)

I can see a similar issue with closed captions. As they get updated only after you change the stream we could only show the proper ones after you change to international which would be different from audio selection.

---

> my international language choice could be stored in local storage

Sure thing, makes sense, will do! I'll save it in the layout data so it gets shared across all of the sessions. I'll also try to save CC info.

---

> Did you perhaps mean support for F1 LIVE? If not, could you clarify?

We've got a few single-stream sessions: _Weekend Warm-Ups_, _Post/Pre-quali Shows_, etc. Those have only one stream — `F1 Live` so I am always falling back to the first available stream in case the one set in the layout doesn't exist.

---

> Shucks. Why can't software development be easy.

At least it earns us not so bad penny 😅

**Comment by toiletgranny** [comment]
> I love the idea and I have actually already thought about doing that but it poses quite a big issue — I only have information about what languages are available after the user opens the international stream. So up until then I don't even know if there are any additional audio streams

Oh, that's unfortunate. Is there any other way we could retrieve the list of available international audio streams without having the user click on the "International" option first? Is there any way of "fake enabling" the international stream only to see what languages are available? If we can't think of any workaround at the moment, I guess I can't think of a better way to handle the UI than what you've already done here.

> I guess we could hardcoded those languages but I don't want to maintain that as I doubt I'll be using International myself too often

While I 100% agree hardcoding isn't the answer, I actually happen to know folks who prefer the Sky sport's English commentary over this year's F1 LIVE commentators. I even had one guy approaching me last week and asking about the support for the international streams. :D So there's def a demand for this.

**Comment by bibixx** [comment]
> While I 100% agree hardcoding isn't the answer, I actually happen to know folks who prefer the Sky sport's English commentary over this year's F1 LIVE commentators.

Oh I mean I don't want to maintain **hardcoded** list of languages. The feature itself is definitely something I want to maintain.

> Is there any other way we could retrieve the list of available international audio streams without having the user click on the "International" option first?

Yeah, there is... I can manually parse the `.m3u8` file that has all of that data. Let me see how complicated it would be

**Pull request merged**
